#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

set -e

# load env vars
for env_var in  $OPENSHIFT_HOMEDIR/.env/*
do
    . $env_var
done

# deploy application configuration files
cp ${OPENSHIFT_REPO_DIR}/.openshift/config_files/database.yml ${OPENSHIFT_REPO_DIR}/config
cp ${OPENSHIFT_REPO_DIR}/.openshift/config_files/providers.yml ${OPENSHIFT_REPO_DIR}/config

# db:migrate
pushd ${OPENSHIFT_REPO_DIR} > /dev/null
bundle exec rake db:migrate RAILS_ENV="production"
popd > /dev/null
