# Add here all non-activerecord model/attributes translations
# This file is NOT autogenerated

#MOCK
_('Providers/mock/mock provider application') #model name translation
_('Providers::Mock::MockProviderApplication|Name') #model attribute translation
_('Providers::Mock::MockProviderApplication|Launchable id')
_('Providers::Mock::MockProviderApplication|State')
N_('helpers.label.providers_mock_mock_provider_application.name') #model attribute label translation
N_('helpers.label.providers_mock_mock_provider_application.launchable_id')
N_('helpers.label.providers_mock_mock_provider_application.state')

#OPENSTACK
_('Providers/open_stack/open_stack provider application')
_('Providers::OpenStack::OpenStackProviderApplication|Name')
_('Providers::OpenStack::OpenStackProviderApplication|Launchable id')
_('Providers::OpenStack::OpenStackProviderApplication|State')
_('Providers::OpenStack::OpenStackProviderApplication|Flavor id')
N_('helpers.label.providers_open_stack_open_stack_provider_application.name')
N_('helpers.label.providers_open_stack_open_stack_provider_application.launchable_id')
N_('helpers.label.providers_open_stack_open_stack_provider_application.state')
N_('helpers.label.providers_open_stack_open_stack_provider_application.flavor_id')

#CONDUCTOR
_('Providers/conductor/conductor provider application')
_('Providers::Conductor::ConductorProviderApplication|Name')
_('Providers::Conductor::ConductorProviderApplication|Launchable id')
_('Providers::Conductor::ConductorProviderApplication|State')
N_('helpers.label.providers_conductor_conductor_provider_application.name')
N_('helpers.label.providers_conductor_conductor_provider_application.launchable_id')
N_('helpers.label.providers_conductor_conductor_provider_application.state')

#OVIRT
_('Providers/ovirt/ovirt provider application')
_('Providers::Ovirt::OvirtProviderApplication|Name')
_('Providers::Ovirt::OvirtProviderApplication|Launchable id')
_('Providers::Ovirt::OvirtProviderApplication|State')
N_('helpers.label.providers_ovirt_ovirt_provider_application.name')
N_('helpers.label.providers_ovirt_ovirt_provider_application.launchable_id')
N_('helpers.label.providers_ovirt_ovirt_provider_application.state')
