source :rubygems

gem 'rails'

gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'haml-rails'
gem 'sass'
gem 'sass-rails'
gem 'psych'
gem 'rbovirt'

group :assets do
  gem 'compass-rails'
  gem 'compass'
  gem 'compass-960-plugin'
end

group :development, :test do
  gem 'debugger'
  gem 'sqlite3'
  gem 'rspec-rails'
end

group :test do
  gem 'capybara'
  gem 'simplecov', :require => false
  gem 'launchy'
  gem 'factory_girl'
end
